DROP DATABASE MUZIKLER

-- MUZIKLER ISMINDE DATABASE YARATILIR
CREATE DATABASE MUZIKLER;

-- BIR KERELIGINE USE DATABASE CALISTIRILIR
USE MUZIKLER

-- SANATCILAR ISMINDE TABLOLAR YARATILIR
CREATE TABLE Sanatcilar(
Sanatci_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Sanatci_Adi VARCHAR(50) NOT NULL,
Sanatci_Sehri VARCHAR(10) NOT NULL);

-- SEHIR'E 10 KARAKTER AZ GELEBÝLÝR DÜÞÜNCESÝYLE TABLOYA MÜDAHALE EDÝLÝR
ALTER TABLE Sanatcilar
ALTER COLUMN Sanatci_Sehri VARCHAR(50) NOT NULL;

-- SANATCILARIN ESERLERI ICIN ESERLER ISMINDE TABLO YARATILIR

CREATE TABLE Eserler(
Eser_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Eser_Ismi VARCHAR(50) NOT NULL,
Eser_Tarihi Date NOT NULL,);

-- BOSTA ESER OLMAMASI ICIN, ESERLER TABLOSUNA FOREIGN KEY SARTI EKLENIR
ALTER TABLE Eserler
ADD Eser_Sanatci_ID INT NOT NULL FOREIGN KEY  REFERENCES Sanatcilar(Sanatci_ID);

-- ESER SANATCI ID ESER ID'DEN SONRA OLSUN ISTIYORUM  BUNUN ICIN YENI TABLO OLUÞTURUP 
-- ESKI TABLOYU SILECEGIM VE PRIMARY, FOREIGN KEY'LERI TEKRAR ATAYACAGIM

SELECT Eser_ID, Eser_Sanatci_ID, Eser_Ismi, Eser_Tarihi
INTO  Eser
FROM Eserler

ALTER TABLE Eser 
ADD PRIMARY KEY (Eser_ID);

ALTER TABLE Eser
ADD FOREIGN KEY (Eser_Sanatci_ID) REFERENCES Sanatcilar(Sanatci_ID);

DROP TABLE Eserler;

EXEC sp_rename 'dbo.Eser', 'Eserler';

-- ESER VE SANATCI GIRMEYE BASLAYALIM, ONCE SANATCI GIRMEMIZ LAZIM CUNKU ESER'DE FOREIGN KEY VAR
-- SANATCI ID OTOMATIK ARTACAGI ICIN ISIM VE SEHIR GIRMEK YETERLI

INSERT INTO Sanatcilar(Sanatci_Adi, Sanatci_Sehri)
VALUES ('Stuart Chatwood', 'Fleetwood'), ('Guillaume David','Greater Lille Metropolitan Area');

-- ESER BILGILERI GIRILIR

INSERT INTO dbo.Eserler(Eser_Sanatci_ID, Eser_Ismi, Eser_Tarihi)

VALUES  ('1','The Sluice', '2022-02-27'), 
		('1','The Shroud of the Deep','2023-05-18'), 
		('2', 'Children of the Omnissiah', '2018-10-06'), 
		('2', 'Noosphere', '2019-11-24');

-- Noosphere'in TARIHINI YANLIS GIRDIK DIYE DUSUNELIM, TARIHI DEGISTIRELIM
UPDATE dbo.Eserler
SET Eser_Tarihi = '2019-05-22' 
WHERE Eser_Ismi = 'Noosphere'; 

-- ORDER BY ORNEGI (ISLEVSIZ)
SELECT * FROM Eserler ORDER BY Eser_Tarihi DESC;

-- 2020'DEN ONCEKI ESERLERI SECMEK ICIN; (ISLEVSIZ)
SELECT * FROM Eserler WHERE (Eser_Tarihi < '2020');

-- ICINDE 'THE' OLANLARI SECME (ISLEVSIZ)
SELECT * FROM Eserler WHERE (Eser_Ismi LIKE '%the%');

-- JOIN ORNEGI (ISLEVSIZ)
SELECT * FROM Eserler 
INNER JOIN Sanatcilar ON Eserler.Eser_Sanatci_ID  = Sanatcilar.Sanatci_ID

-- SANATCILARIN SARKI SAYISINI GOSTEREN KOD(ISLEVSIZ)
SELECT Sanatci_Adi, COUNT(Eser_ID) AS 'Þarký Sayýsý' FROM Sanatcilar JOIN Eserler 
ON Eser_Sanatci_ID = Sanatci_ID GROUP BY Sanatci_Adi

-- VIEW OLUSTURMA ORNEGI 
CREATE VIEW [ViewOrnek]
AS  
SELECT Sanatci_Adi, Sanatci_Sehri, Eser_Ismi, Eser_Tarihi FROM Sanatcilar 
INNER JOIN Eserler ON Eserler.Eser_Sanatci_ID = Sanatcilar.Sanatci_ID;

-- BIRAZ DAHA ESER EKLEME
INSERT INTO dbo.Eserler(Eser_Sanatci_ID, Eser_Ismi, Eser_Tarihi)
VALUES ('1', 'Conflict in the Tangle', '2021-06-15'),
	   ('1', 'Traverse the Mountain',  '2021-07-11'),
	   ('1', 'Battle of the Mountain', '2023-01-07');

-- ESERLERI 1-2-3-4 DEGIL DE 1-4-2-3 OLARAK SIRALAMA ARDINDAN NORMAL DEVAM ETTIRME
-- (WHERE Eser_ID IN (1,2,3,4) DIYEREK SADECE 4 UNU ALABILIRIZ)
SELECT * 
FROM   Eserler
ORDER BY
       CASE 
		    WHEN Eser_ID = 4 THEN 2
            WHEN Eser_ID = 2 THEN 3
		    WHEN Eser_ID = 3 THEN 4
			-- WHEN Eser_Ismi = 'Traverse the Mountain' THEN 0 -- LISTENIN BASINA TASIMA
			WHEN Eser_ID = Eser_ID THEN  Eser_ID -- BUNU SONA KOYMAZSAK 1-2-3-4 DIYE SIRALAR
       END

-- CIKIS TARIHINI ALIP HANGI AY CIKTIGINI YAZAN BIR FONKSIYON
CREATE FUNCTION DBO.GETMONTHNAME(@DATE AS DATETIME) 
RETURNS VARCHAR(10)
AS
BEGIN
DECLARE @RESULT AS VARCHAR(10)

	IF DATEPART(MONTH, @DATE )=1 SET @RESULT= '01.OCAK' 
	IF DATEPART(MONTH, @DATE )=2 SET @RESULT= '02.ÞUBAT' 
	IF DATEPART(MONTH, @DATE )=3 SET @RESULT= '03.MART' 
	IF DATEPART(MONTH, @DATE )=4 SET @RESULT= '04.NÝSAN' 
	IF DATEPART(MONTH, @DATE )=5 SET @RESULT= '05.MAYIS' 
	IF DATEPART(MONTH, @DATE )=6 SET @RESULT= '06.HAZÝRAN' 
	IF DATEPART(MONTH, @DATE )=7 SET @RESULT= '07.TEMMUZ' 
	IF DATEPART(MONTH, @DATE )=8 SET @RESULT= '08.AÐUSTOS' 
	IF DATEPART(MONTH, @DATE )=9 SET @RESULT= '09.EYLÜL' 
	IF DATEPART(MONTH, @DATE )=10 SET @RESULT= '10.EKÝM' 
	IF DATEPART(MONTH, @DATE )=11 SET @RESULT= '11.KASIM' 
	IF DATEPART(MONTH, @DATE )=12 SET @RESULT= '12.ARALIK'

	RETURN @RESULT
END

-- FONKSIYONA DEGER VERIP SONUCA BAKALIM
SELECT dbo.GETMONTHNAME(Eser_Tarihi) AS Eser_Cikis_Ayi FROM Eserler

-- VIEW ORNEGIMIZI DEGISTIRIP CIKIS AYINI SONA EKLEYELIM
ALTER VIEW [ViewOrnek]
AS  
SELECT Sanatci_Adi, Sanatci_Sehri, Eser_Ismi, Eser_Tarihi, dbo.GETMONTHNAME(Eser_Tarihi) AS 'Çýkýþ Ayý'
FROM Sanatcilar 
INNER JOIN Eserler ON Eserler.Eser_Sanatci_ID = Sanatcilar.Sanatci_ID;

SELECT * FROM ViewOrnek

-- STORED PROCEDURE OLUSTURMA 
CREATE PROCEDURE EserCikisTarihiBul
@Eser VARCHAR(60)
AS
SELECT Eser_Tarihi FROM Eserler 
WHERE Eser_Ismi = @Eser;

-- STORED PROCEDURE CALISTIRMA 
EXEC EserCikisTarihiBul 'The Sluice';

